### ISSUE TITLE
Using this library in the browser

### ISSUE THREAD

**Issue by frandiox** [ffalt/pdf.js-extract#11]
Hi! Thanks a lot for this library. I'm using `PDFExtract.extractBuffer` from the browser and it works perfectly to find text in a PDF. The only problem is the stubs added for the Node environment. I understand this library is meant to be used in Node but it basically eases PDF.js usage for my use case a lot.

Would you consider adding stubs only if they are not present already or making a different entry point for browser? (without 'fs' and 'stubs' dependencies).

Otherwise, could you please explain what did you remove from PDF.js to make it more lightweight? Thanks!

**Comment by ffalt** [comment]
Hi! Could you please explain how it is easier to use this library rather than use pdf.js itself? IMHO, overall it would be easier to just install pdfjs-dist from npm, copy the function PDFExtract.extractBuffer, very little would have to change.

Nevertheless, I'm open to add a different entry point if you pull request it. But there is a difficulty, for some pdfs with unicode text, binary font files are loaded via nodejs fs. These must be included into the browser project somehow.

I did not remove anything from pdf.js (as far I'm aware of). This package includes a bundled version out of the same build system as the official [pdfjs-dist](https://www.npmjs.com/package/pdfjs-dist) is bundled. Only difference is, in this package, the npm dependencies packages needed only to build pdfjs and the browser are not included.

**Comment by frandiox** [comment]
@ffalt 	I see, I thought you modified PDF.js. Yes, the only necessary code is indeed `PDFExtract.extractBuffer`, so I guess I'll just copy that code. Thanks again!

**Comment by DoneDeal0** [comment]
Hi, have you managed to use this lib directly in the browser? When removing "fs" module and extract method the index.js file oin the source code, I still get the error "can't resolve fs".

**Comment by frandiox** [comment]
Yeah. As mentioned by the author, I just copied `extractBuffer` function (as a function, not as a class) from https://github.com/ffalt/pdf.js-extract/blob/main/lib/index.js#L43 to my app code, and then imported pdfjs at the top of the file. Basically you'll end up with something like:

```js
import pdfjsLib from 'pdfjs-dist'

function extractBuffer(buffer, options, cb) {
// ... Remove any `this.` match from the original code
}
```

There's no `fs` there.

**Comment by DoneDeal0** [comment]
Ok thanks. Would you have an exemple by chance? It doesn't work for me.
