### ISSUE TITLE
Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined"

### ISSUE THREAD

**Issue by Ziv-Barber** [ffalt/pdf.js-extract#15]
Not really working. I just tried to copy the simple example into an electron application and I got the error: "Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined""

**Comment by ffalt** [comment]
Please describe how you integrated the node module into the electron app. 

I just copied the the simple example into the [electron-quick-start](https://github.com/electron/electron-quick-start), called it in the main.js and had the result in the console. 

My best guess: make sure the module is used in the node process, not then chromium process. since pdf.js-extract won't work in a browser context.

**Comment by Ziv-Barber** [comment]
Since that I need the node version and not the web version I had to move to use pdf2json, the node.js version of pdf.js and the only pdf library working with node.js. That's fixed everything for me.

**Comment by ffalt** [comment]
hu? pdf.js-extract is a **node.js library** which is **not** working in the browser, so your claim that pdf2json is the only pdf library for node.js is wrong. anyhow, pdf2json is working for you, so everything is fine.
