### ISSUE TITLE
Some characters not being extracted

### ISSUE THREAD

**Issue by bobsquito** [ffalt/pdf.js-extract#30]
I use this package to get the text out of pdfs to make them searchable. Occasionally some characters are extracted as unknown symbols (displayed as boxes).

The following characters display as 003 on the pdf but for some reason are extracted as \x00 which is a hex code for null I think.
```
{
  x: 139.8924901141838,
  y: 192.57599427999992,
  str: '\x00',
  dir: 'ltr',
  width: 5.62011142035425,
  height: 10.504880634296622,
  fontName: 'g_d0_f2'
},
{
  x: 145.51259390011606,
  y: 192.57599427999992,
  str: '\x00',
  dir: 'ltr',
  width: 5.62011142035425,
  height: 10.504880634296622,
  fontName: 'g_d0_f2'
},
{
  x: 151.1326976860483,
  y: 192.57599427999992,
  str: '\x00',
  dir: 'ltr',
  width: 5.62011142035425,
  height: 10.504880634296622,
  fontName: 'g_d0_f2'
}
```

**Comment by ffalt** [comment]
Hi! Could you please add an example pdf to reproduce? This library is only a wrapper around https://github.com/mozilla/pdf.js/ so probably the cause is not in pdfs.js-extract, but I will see if I can help.

**Comment by bobsquito** [comment]
Thanks for your help. Is there a way I can email it to you as I don't really want the pdf posted publicly?

I think it might be something odd with pdf.js as when I open the document with Firefox (which uses pdf.js to display them) then I can't copy those characters, but they do display correctly. The rest of the document can be highlighted and copied. It seems to know that it is text because it comes through as \x00 but when opened in firefox those characters look the same as if they were an image.

**Comment by ffalt** [comment]
I don't have much hope, but you can send me an example to ffalty@gmail.com
Please make sure there are no sensitve data from private third persons in the pdf.

**Comment by ffalt** [comment]
Sorry for my late reply, I had to work on other things and then I almost forgot. 
I looked at the file and my best guess is: this is a bug/incompleteness in the pdf file itself. pdf.js can draw every sign/letter in a font, but not necessarily knows which letter it is in a text representation. For that it needs complete /ToUnicode data. Read more [here](https://github.com/mozilla/pdf.js/issues/12581#issuecomment-722450401). That's why your may PDF looks fine, but copy&paste is gibberish & zeros. 
So pdf.js (here in Firefox) can present the "V" but not the number following it. 
<img width="528" alt="screenshot-ff-pdfjs" src="https://user-images.githubusercontent.com/3438714/152951637-1bf76585-fd9d-4c58-acd0-b3a651e88853.png">
I tried using some PDF structure analyser like [i7j-rups](https://github.com/itext/i7j-rups) but did not had the time for a proper in-depth analysis. So I'm not 100% sure on this, strangely copy&pasting in Chrome (they use PDFium) is fine, so either they use OCR or this is really a bug in pdf.js.
